import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Transmorgify",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster
          position="top-center"
          toastOptions={{
            unstyled: true,
            classNames: {
              error: "text-mediumSlateBlue flex items-center space-x-2",
              warning: "text-mediumSlateBlue flex items-center space-x-2",
              success: "text-heliotrope flex items-center space-x-2",
              loading: "text-heliotrope flex items-center space-x-2",
              info: "text-mediumSlateBlue flex items-center space-x-2",
            },
          }}
        />
        {children}
      </body>
    </html>
  );
}
